<?php

declare(strict_types=1);

namespace Corbpie\NBALive\Dto;

/**
 * Normalized team standing entry.
 */
final readonly class TeamStanding
{
    public function __construct(
        public int $leagueRank,
        public int $teamId,
        public string $team,
        public string $conference,
        public string $division,
        public int|float $wins,
        public int|float $losses,
        public float $winPct,
        public int|float $gp,
        public int|float $leagueGamesBack,
        public int|float $ptsPg,
        public int|float $oppPtsPg,
        public int|float $diffPtsPg,
        public int|float $totalPts,
        public int|float $oppTotalPts,
        public int|float $diffTotalPts,
        public string $homeRecord,
        public string $roadRecord,
        public string $ot,
        public string $threePtsOrLess,
        public string $tenPtsOrMore,
        public int|float $longestWStreak,
        public int|float $longestLStreak,
        public int|float $currentHomeStreak,
        public int|float $currentRoadStreak,
        public int|float $currentStreak,
        public int|float $confGamesBack,
        public int|float $divGamesBack,
        public int|float $clinchedPlayoffs,
        public int|float $clinchedPlayin,
        public int|float $eliminatedConf,
        public string $aheadAtHalf,
        public string $behindAtHalf,
        public string $tiedAtHalf,
        public string $aheadAtThird,
        public string $behindAtThird,
        public string $tiedAtThird,
        public string $scored100Pts,
        public string $oppScored100Pts,
        public string $oppOver500,
        public string $leadFgp,
        public string $leadReb,
        public string $fewerTov,
        public int|float $vsEast,
        public int|float $vsWest,
        public int|float $vsAtlantic,
        public int|float $vsCentral,
        public int|float $vsSoutheast,
        public int|float $vsNorthwest,
        public int|float $vsPacific,
        public int|float $vsSouthwest,
    ) {
    }

    /**
     * @param array<string, mixed> $row
     */
    public static function fromResultSetRow(array $row, int $leagueRank): self
    {
        $wins = (int) ($row['WINS'] ?? $row['W'] ?? 0);
        $losses = (int) ($row['LOSSES'] ?? $row['L'] ?? 0);

        return new self(
            leagueRank: $leagueRank,
            teamId: (int) ($row['TeamID'] ?? $row['TEAM_ID'] ?? 0),
            team: (string) ($row['TeamName'] ?? $row['TEAM_NAME'] ?? ''),
            conference: (string) ($row['Conference'] ?? $row['CONFERENCE'] ?? ''),
            division: (string) ($row['Division'] ?? $row['DIVISION'] ?? ''),
            wins: $wins,
            losses: $losses,
            winPct: (float) ($row['WinPCT'] ?? $row['WIN_PCT'] ?? $row['W_PCT'] ?? 0),
            gp: $wins + $losses,
            leagueGamesBack: (float) ($row['LeagueGamesBack'] ?? $row['LEAGUE_GAMES_BACK'] ?? 0),
            ptsPg: (float) ($row['PointsPG'] ?? $row['PTS_PG'] ?? 0),
            oppPtsPg: (float) ($row['OppPointsPG'] ?? $row['OPP_PTS_PG'] ?? 0),
            diffPtsPg: (float) ($row['DiffPointsPG'] ?? $row['DIFF_PTS_PG'] ?? 0),
            totalPts: (int) ($row['TotalPoints'] ?? $row['TOTAL_PTS'] ?? 0),
            oppTotalPts: (int) ($row['OppTotalPoints'] ?? $row['OPP_TOTAL_PTS'] ?? 0),
            diffTotalPts: (int) ($row['DiffTotalPoints'] ?? $row['DIFF_TOTAL_PTS'] ?? 0),
            homeRecord: trim((string) ($row['HOME_RECORD'] ?? $row['HomeRecord'] ?? '')),
            roadRecord: trim((string) ($row['ROAD_RECORD'] ?? $row['RoadRecord'] ?? '')),
            ot: trim((string) ($row['OT'] ?? '')),
            threePtsOrLess: trim((string) ($row['ThreePTSOrLess'] ?? $row['3PTS_OR_LESS'] ?? '')),
            tenPtsOrMore: trim((string) ($row['TenPTSOrMore'] ?? $row['10PTS_OR_MORE'] ?? '')),
            longestWStreak: (int) ($row['LongestWinStreak'] ?? $row['LONGEST_W_STREAK'] ?? 0),
            longestLStreak: (int) ($row['LongestLossStreak'] ?? $row['LONGEST_L_STREAK'] ?? 0),
            currentHomeStreak: (int) ($row['CurrentHomeStreak'] ?? $row['CURRENT_HOME_STREAK'] ?? 0),
            currentRoadStreak: (int) ($row['CurrentRoadStreak'] ?? $row['CURRENT_ROAD_STREAK'] ?? 0),
            currentStreak: (int) ($row['CurrentStreak'] ?? $row['CURRENT_STREAK'] ?? 0),
            confGamesBack: (float) ($row['ConferenceGamesBack'] ?? $row['CONF_GAMES_BACK'] ?? 0),
            divGamesBack: (float) ($row['DivisionGamesBack'] ?? $row['DIV_GAMES_BACK'] ?? 0),
            clinchedPlayoffs: (int) ($row['ClinchedPlayoffs'] ?? $row['CLINCHED_PLAYOFFS'] ?? 0),
            clinchedPlayin: (int) ($row['ClinchedPlayIn'] ?? $row['CLINCHED_PLAYIN'] ?? 0),
            eliminatedConf: (int) ($row['EliminatedConference'] ?? $row['ELIMINATED_CONF'] ?? 0),
            aheadAtHalf: trim((string) ($row['AheadAtHalf'] ?? $row['AHEAD_AT_HALF'] ?? '')),
            behindAtHalf: trim((string) ($row['BehindAtHalf'] ?? $row['BEHIND_AT_HALF'] ?? '')),
            tiedAtHalf: trim((string) ($row['TiedAtHalf'] ?? $row['TIED_AT_HALF'] ?? '')),
            aheadAtThird: trim((string) ($row['AheadAtThird'] ?? $row['AHEAD_AT_THIRD'] ?? '')),
            behindAtThird: trim((string) ($row['BehindAtThird'] ?? $row['BEHIND_AT_THIRD'] ?? '')),
            tiedAtThird: trim((string) ($row['TiedAtThird'] ?? $row['TIED_AT_THIRD'] ?? '')),
            scored100Pts: trim((string) ($row['Scored100PTS'] ?? $row['SCORED_100_PTS'] ?? '')),
            oppScored100Pts: trim((string) ($row['OppScored100PTS'] ?? $row['OPP_SCORED_100_PTS'] ?? '')),
            oppOver500: trim((string) ($row['OppOver500'] ?? $row['OPP_OVER_500'] ?? '')),
            leadFgp: trim((string) ($row['LeadFGP'] ?? $row['LEAD_FGP'] ?? '')),
            leadReb: trim((string) ($row['LeadREB'] ?? $row['LEAD_REB'] ?? '')),
            fewerTov: trim((string) ($row['FewerTOV'] ?? $row['FEWER_TOV'] ?? '')),
            vsEast: (int) ($row['VsEast'] ?? $row['VS_EAST'] ?? 0),
            vsWest: (int) ($row['VsWest'] ?? $row['VS_WEST'] ?? 0),
            vsAtlantic: (int) ($row['VsAtlantic'] ?? $row['VS_ATLANTIC'] ?? 0),
            vsCentral: (int) ($row['VsCentral'] ?? $row['VS_CENTRAL'] ?? 0),
            vsSoutheast: (int) ($row['VsSoutheast'] ?? $row['VS_SOUTHEAST'] ?? 0),
            vsNorthwest: (int) ($row['VsNorthwest'] ?? $row['VS_NORTHWEST'] ?? 0),
            vsPacific: (int) ($row['VsPacific'] ?? $row['VS_PACIFIC'] ?? 0),
            vsSouthwest: (int) ($row['VsSouthwest'] ?? $row['VS_SOUTHWEST'] ?? 0),
        );
    }

    /**
     * @return array<string, float|int|string>
     */
    public function toArray(): array
    {
        return [
            'league_rank' => $this->leagueRank,
            'team_id' => $this->teamId,
            'team' => $this->team,
            'conference' => $this->conference,
            'division' => $this->division,
            'wins' => $this->wins,
            'losses' => $this->losses,
            'win_pct' => $this->winPct,
            'gp' => $this->gp,
            'league_games_back' => $this->leagueGamesBack,
            'pts_pg' => $this->ptsPg,
            'opp_pts_pg' => $this->oppPtsPg,
            'diff_pts_pg' => $this->diffPtsPg,
            'total_pts' => $this->totalPts,
            'opp_total_pts' => $this->oppTotalPts,
            'diff_total_pts' => $this->diffTotalPts,
            'home_record' => $this->homeRecord,
            'road_record' => $this->roadRecord,
            'ot' => $this->ot,
            '3pts_or_less' => $this->threePtsOrLess,
            '10pts_or_more' => $this->tenPtsOrMore,
            'longest_w_streak' => $this->longestWStreak,
            'longest_l_streak' => $this->longestLStreak,
            'current_home_streak' => $this->currentHomeStreak,
            'current_road_streak' => $this->currentRoadStreak,
            'current_streak' => $this->currentStreak,
            'conf_games_back' => $this->confGamesBack,
            'div_games_back' => $this->divGamesBack,
            'clinched_playoffs' => $this->clinchedPlayoffs,
            'clinched_playin' => $this->clinchedPlayin,
            'eliminated_conf' => $this->eliminatedConf,
            'ahead_at_half' => $this->aheadAtHalf,
            'behind_at_Half' => $this->behindAtHalf,
            'tied_at_half' => $this->tiedAtHalf,
            'ahead_at_third' => $this->aheadAtThird,
            'behind_at_third' => $this->behindAtThird,
            'tied_at_third' => $this->tiedAtThird,
            'scored_100_pts' => $this->scored100Pts,
            'opp_scored_100_pts' => $this->oppScored100Pts,
            'opp_over_500' => $this->oppOver500,
            'lead_fgp' => $this->leadFgp,
            'lead_reb' => $this->leadReb,
            'fewer_tov' => $this->fewerTov,
            'vs_east' => $this->vsEast,
            'vs_west' => $this->vsWest,
            'vs_atlantic' => $this->vsAtlantic,
            'vs_central' => $this->vsCentral,
            'vs_southeast' => $this->vsSoutheast,
            'vs_northwest' => $this->vsNorthwest,
            'vs_pacific' => $this->vsPacific,
            'vs_southwest' => $this->vsSouthwest,
        ];
    }
}
